### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by filmaj** [adobe/css-pseudo-elements#1]
Hello @astearns ,
My name is Fil and I’m from Adobe’s Open Source Office. I see this project has been inactive for a long time. Just wondering: is there still value in keeping this project around? Do we foresee community usage/activity happening around this project?

If yes, can I send some pull requests to update the documentation? At a minimum we need contribution guidelines that reference requiring the signing of [Adobe’s CLA](http://opensource.adobe.com/cla.html).

If no, is it OK if we archive this project?

Thanks for any info.

-Fil

**Comment by astearns** [comment]
@filmaj it would be fine to archive this project.

**Comment by oslego** [comment]
Ah, good memories from proto-Adobe Web Platform.
It's ok to archive this project. Thanks for the trip down memory lane. :)

**Comment by filmaj** [comment]
Thanks for the responses everyone! I will archive the repo.
